languageCode = "en-us"
title = "tlehman@home"
baseURL = "/"
theme = "blank"
paginate = 3

[[menu.main]]
    name = "About"
    pre = ""
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Contact"
    pre = ""
    weight = -100
    url = "/contact/"

