languageCode = "en-us"
title = "tlehman@home"
baseURL = "https://tobilehman.com"
theme = "blank"

[[menu.main]]
    name = "About"
    pre = ""
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "Contact"
    pre = ""
    weight = -100
    url = "/contact/"